# GoAccess — Apache combined Log-Format
log-format COMBINED
date-format %d/%b/%Y
time-format %H:%M:%S

# WebSocket läuft intern auf 7890, extern auf 17890
# ws-url muss auf den extern erreichbaren Port zeigen
real-time-html true
port 7890
addr 0.0.0.0

output /srv/report/index.html

# Bot-Erkennung
ignore-crawlers false

enable-panel VISITORS
enable-panel REQUESTS
enable-panel REQUESTS_STATIC
enable-panel NOT_FOUND
enable-panel HOSTS
enable-panel OS
enable-panel BROWSERS
enable-panel VISIT_TIMES
enable-panel REFERRERS
enable-panel REFERRING_SITES
enable-panel STATUS_CODES

color-scheme 2
